//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Forms.
        /// </summary>
        internal static string AvailableForms {
            get {
                return ResourceManager.GetString("AvailableForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this window.
        /// </summary>
        internal static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Form.
        /// </summary>
        internal static string CreateForm {
            get {
                return ResourceManager.GetString("CreateForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TextBook.
        /// </summary>
        internal static string CreateTextBook {
            get {
                return ResourceManager.GetString("CreateTextBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to čeština.
        /// </summary>
        internal static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Google Docs.
        /// </summary>
        internal static string ExportToGoogleDocs {
            get {
                return ResourceManager.GetString("ExportToGoogleDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        internal static string Filled {
            get {
                return ResourceManager.GetString("Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Forms.
        /// </summary>
        internal static string FilledForms {
            get {
                return ResourceManager.GetString("FilledForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling In Progress.
        /// </summary>
        internal static string FillingInProgress {
            get {
                return ResourceManager.GetString("FillingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form filling ended.
        /// </summary>
        internal static string FormFillingEnded {
            get {
                return ResourceManager.GetString("FormFillingEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Fills.
        /// </summary>
        internal static string FormFills {
            get {
                return ResourceManager.GetString("FormFills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        internal static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google account email.
        /// </summary>
        internal static string GoogleAccountEmail {
            get {
                return ResourceManager.GetString("GoogleAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google account password.
        /// </summary>
        internal static string GoogleAccountPassword {
            get {
                return ResourceManager.GetString("GoogleAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from Google Group.
        /// </summary>
        internal static string ImportFromGoogleGroup {
            get {
                return ResourceManager.GetString("ImportFromGoogleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in.
        /// </summary>
        internal static string KeepMeSignedIn {
            get {
                return ResourceManager.GetString("KeepMeSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        internal static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NamePerson {
            get {
                return ResourceManager.GetString("NamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameThing {
            get {
                return ResourceManager.GetString("NameThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire.
        /// </summary>
        internal static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen the Form window.
        /// </summary>
        internal static string ReopenFormWindow {
            get {
                return ResourceManager.GetString("ReopenFormWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen Window.
        /// </summary>
        internal static string ReopenWindow {
            get {
                return ResourceManager.GetString("ReopenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solver.
        /// </summary>
        internal static string Solver {
            get {
                return ResourceManager.GetString("Solver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Submited.
        /// </summary>
        internal static string SuccessfulySubmited {
            get {
                return ResourceManager.GetString("SuccessfulySubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBooks.
        /// </summary>
        internal static string TextBooks {
            get {
                return ResourceManager.GetString("TextBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times filled.
        /// </summary>
        internal static string TimesFilled {
            get {
                return ResourceManager.GetString("TimesFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Test.
        /// </summary>
        internal static string TrainingTest {
            get {
                return ResourceManager.GetString("TrainingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        internal static string UserGroups {
            get {
                return ResourceManager.GetString("UserGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
